### ISSUE TITLE
Enlarge QR codes on hover does not work with 10.8

### ISSUE THREAD

**Issue by wkloucek** [owncloud/theme-qnap#3]
![image](https://user-images.githubusercontent.com/34452982/123210442-4b7a9200-d4c2-11eb-81b6-f6a8d2f26e0b.png)

**Comment by wkloucek** [comment]
@ChrisEdS @hurradieweltgehtunter can one of you have a look why the QR codes hovering does not work anymore with Core 10.8 beta?

**Comment by hurradieweltgehtunter** [comment]
This has nothing to do with 10.8.
AFAIK the hovering effect got removed, I had a discussion with @ChrisEdS about it. I checked the JS files and theres no hovering effect implemented.

**Comment by wkloucek** [comment]
@hurradieweltgehtunter  with 10.7 (`docker run -e OWNCLOUD_DOMAIN=localhost:8080 -p 8080:8080 owncloud/qnap:10.7`) it works: 
![image](https://user-images.githubusercontent.com/34452982/123276586-97025f80-d505-11eb-99c9-156829e6a65f.png)

I also have the enlarge css in both cases:
```
/* Zoom for Login QR-code */

.enlarge:hover {
  z-index: 9999;
  transform: scale(2);
  transition: transform .2s;
}
```

**Comment by ChrisEdS** [comment]
https://github.com/owncloud/theme-qnap/blob/e88e16a39a03f439993e5ae3491d1b4ab55d4c95/core/css/styles.css#L21-L25

It's still part of the QNAP-Theme.

**Comment by wkloucek** [comment]
> This has nothing to do with 10.8.
> AFAIK the hovering effect got removed, I had a discussion with @ChrisEdS about it. I checked the JS files and theres no hovering effect implemented.

> https://github.com/owncloud/theme-qnap/blob/e88e16a39a03f439993e5ae3491d1b4ab55d4c95/core/css/styles.css#L21-L25
> 
> It's still part of the QNAP-Theme.

Yes, it is still part of the QNAP Theme, but the hovering doesn't work anymore with ownCloud 10.8 Beta 1. Do you have an idea why?

**Comment by wkloucek** [comment]
@ChrisEdS I had a look why the `enlarge` css rule isn't applied and it is because the `#body-login footer *.show` rule from core (introduced with 10.8) wins.

![image](https://user-images.githubusercontent.com/34452982/123424698-7c8dbc00-d5c1-11eb-8282-ea11eb64f095.png)

I added a PR #4 to fix this. But unfortunately I couldn't get the QR code above the text. Therefore it looks like this currently:
![image](https://user-images.githubusercontent.com/34452982/123429717-8dd9c700-d5c7-11eb-88e6-f7796c308750.png)

@ChrisEdS Do you have an idea why the z-index is not winning over the text below the QR codes?

**Comment by ChrisEdS** [comment]
Please add the following to the `styles.css` file:

```
#body-login p.info {
    z-index: 0;
}

#body-login footer *.show {
    position: relative;
}

#body-login .mobile,
#body-login .desktop {
    z-index: 1000;
}
```
